name: GKE CI/CD Pipeline

on:
  push:
    paths:
      - "src/**"
      - ".github/workflows/**"
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ secrets.REGION }}
      REPO_NAME: ${{ secrets.REPO_NAME }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

    steps:
      - name: Echo test
        run: echo "${{ env.REGION }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker auth for GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build Docker image
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest ./src

      - name: Push image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

      - name: Update deployment.yaml with new image tag
        run: |
          IMAGE_URI="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest"
          sed -i "s|image: .*|image: $IMAGE_URI|" ./manifests/project/deploy-web.yaml

      - name: Commit and push manifest
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add ./manifests/project/deploy-web.yaml
          git commit -m "Update image to latest: $IMAGE_URI"
          git push
