apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: deploy-web
  name: deploy-web
  namespace: karasuit
spec:
  revisionHistoryLimit: 1
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-web
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-web
    spec:
      serviceAccountName: default
      containers:
        # Imageがハードコーディングされているので使用するときは修正必要
        - image: asia-northeast1-docker.pkg.dev/<プロジェクトID>/dev-karasuit-web-repo/my-app:20250606205230
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          name: web
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: MY_CONFIG_VALUE
              valueFrom:
                configMapKeyRef:
                  name: web-cm
                  key: MY_CONFIG_VALUE
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
